name: Inventory Sync - Nationwide Plants

on:
  schedule:
    # Run inventory sync every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run even if disabled in database'
        required: false
        type: boolean
        default: false

jobs:
  inventory-sync-nationwide-plants:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Check if inventory sync is enabled
      id: check-config
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        if [ "${{ github.event.inputs.force_run }}" = "true" ]; then
          echo "force_run=true" >> $GITHUB_OUTPUT
          echo "enabled=true" >> $GITHUB_OUTPUT
          echo "Inventory sync forced to run"
        else
          # Check if inventory sync is enabled in database
          ENABLED=$(node -e "
            const { RetailerService } = require('./scripts/utils/retailer-service');
            
            async function checkInventorySync() {
              try {
                const retailerService = new RetailerService();
                const retailer = await retailerService.loadRetailerById('nationwide-plants');
                if (retailer.settings && retailer.settings.syncInventory) {
                  console.log('true');
                } else {
                  console.log('false');
                }
              } catch (error) {
                console.error('Error checking database:', error.message);
                console.log('false');
              }
            }
            
            checkInventorySync();
          ")
          echo "enabled=$ENABLED" >> $GITHUB_OUTPUT
          if [ "$ENABLED" = "true" ]; then
            echo "Inventory sync is enabled for Nationwide Plants (from database)"
          else
            echo "Inventory sync is disabled for Nationwide Plants (from database)"
          fi
        fi
      
    - name: Run Nationwide Plants Inventory Sync
      if: steps.check-config.outputs.force_run == 'true' || steps.check-config.outputs.enabled == 'true'
      env:
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        SHOPIFY_LGL_TOKEN: ${{ secrets.SHOPIFY_LGL_TOKEN }}
        SHOPIFY_NATIONWIDE_PLANTS_TOKEN: ${{ secrets.SHOPIFY_NATIONWIDE_PLANTS_TOKEN }}
        EMAIL_FROM: admin@livegoodlogistics.com
        EMAIL_TO: justin@livegoodlogistics.com
        LOG_LEVEL: info
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        echo "Running Nationwide Plants inventory sync"
        node inventory-sync/retailers/nationwide-plants.js
        
    - name: Skip sync (disabled in database)
      if: steps.check-config.outputs.force_run != 'true' && steps.check-config.outputs.enabled != 'true'
      run: |
        echo "Skipping Nationwide Plants inventory sync - disabled in database"
        echo "To force run, use the workflow_dispatch with force_run=true"
        echo "To enable, update the sync_inventory field in the database for nationwide-plants"
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: inventory-sync-nationwide-plants-logs-${{ github.run_id }}
        path: logs/inventory-sync-nationwide-plants-*.log
        retention-days: 7