name: Inventory Sync

on:
  schedule:
    # Run inventory sync every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      retailer:
        description: 'Specific retailer to process (leave empty for all)'
        required: false
        type: choice
        options:
          - all
          - nationwide-plants-config
          - test-store

jobs:
  inventory-sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Run Inventory Sync
      env:
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        SHOPIFY_LGL_TOKEN: ${{ secrets.SHOPIFY_LGL_TOKEN }}
        SHOPIFY_NATIONWIDE_PLANTS_TOKEN: ${{ secrets.SHOPIFY_NATIONWIDE_PLANTS_TOKEN }}
        SHOPIFY_TEST_TOKEN: ${{ secrets.SHOPIFY_TEST_TOKEN }}
        EMAIL_FROM: admin@livegoodlogistics.com
        EMAIL_TO: justin@livegoodlogistics.com
        LOG_LEVEL: info
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        RETAILER_ID: ${{ github.event.inputs.retailer != 'all' && github.event.inputs.retailer || '' }}
      run: |
        echo "Running inventory sync"
        if [ -n "$RETAILER_ID" ]; then
          echo "Processing specific retailer: $RETAILER_ID"
        else
          echo "Processing all retailers with inventory sync enabled"
        fi
        
        node scripts/process-inventory.js
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: inventory-sync-logs-${{ github.run_id }}
        path: logs/
        retention-days: 7
        
    - name: Notify on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#alerts'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
