name: Shopify Sync

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - orders
        - fulfillments
        - inventory
      retailer:
        description: 'Specific retailer ID (optional)'
        required: false
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Shopify sync
      env:
        OPERATION: ${{ github.event.inputs.operation || 'all' }}
        RETAILER_ID: ${{ github.event.inputs.retailer || '' }}
        SHOPIFY_LGL_TOKEN: ${{ secrets.SHOPIFY_LGL_TOKEN }}
        SHOPIFY_TEST_TOKEN: ${{ secrets.SHOPIFY_TEST_TOKEN }}
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      run: |
        if [ -n "$RETAILER_ID" ]; then
          RETAILER_ID=$RETAILER_ID node scripts/process-all.js $OPERATION
        else
          node scripts/process-all.js $OPERATION
        fi
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sync-logs
        path: logs/ 