name: Shopify Sync System

on:
  schedule:
    # Fulfillment processing - every 30 minutes (reduced from 5 minutes)
    - cron: '*/30 * * * *'
    # Order imports - every 2 hours (reduced from 15 minutes)
    - cron: '0 */2 * * *'
    # Inventory sync - every 4 hours (reduced from 30 minutes)
    - cron: '0 */4 * * *'
    # Full sync with summary - every 6 hours (reduced from 2 hours)
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - fulfillments
          - orders
          - inventory

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Run Shopify Sync
      env:
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        SHOPIFY_LGL_TOKEN: ${{ secrets.SHOPIFY_LGL_TOKEN }}
        SHOPIFY_NATIONWIDE_PLANTS_TOKEN: ${{ secrets.SHOPIFY_NATIONWIDE_PLANTS_TOKEN }}
        SHOPIFY_TEST_TOKEN: ${{ secrets.SHOPIFY_TEST_TOKEN }}
        EMAIL_FROM: admin@livegoodlogistics.com
        EMAIL_TO: justin@livegoodlogistics.com
        LOG_LEVEL: info
      run: |
        # Determine operation based on cron schedule or manual input
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          OPERATION="${{ github.event.inputs.operation }}"
        else
          # Determine operation based on cron schedule
          CRON_EXPR="${{ github.event.schedule }}"
          if [[ "$CRON_EXPR" == "*/30 * * * *" ]]; then
            OPERATION="fulfillments"
          elif [[ "$CRON_EXPR" == "0 */2 * * *" ]]; then
            OPERATION="orders"
          elif [[ "$CRON_EXPR" == "0 */4 * * *" ]]; then
            OPERATION="inventory"
          elif [[ "$CRON_EXPR" == "0 */6 * * *" ]]; then
            OPERATION="all"
          else
            OPERATION="all"
          fi
        fi
        
        echo "Running operation: $OPERATION"
        node scripts/process-all.js $OPERATION
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sync-logs-${{ github.run_id }}
        path: logs/
        retention-days: 7
        
    - name: Notify on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#alerts'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 