name: Order Import Sync

on:
  schedule:
    # Run full sync every 30 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - fulfillments
          - orders

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Run Shopify Sync
      env:
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        SHOPIFY_LGL_TOKEN: ${{ secrets.SHOPIFY_LGL_TOKEN }}
        SHOPIFY_NATIONWIDE_PLANTS_TOKEN: ${{ secrets.SHOPIFY_NATIONWIDE_PLANTS_TOKEN }}
        SHOPIFY_TEST_TOKEN: ${{ secrets.SHOPIFY_TEST_TOKEN }}
        EMAIL_FROM: admin@livegoodlogistics.com
        EMAIL_TO: justin@livegoodlogistics.com
        LOG_LEVEL: info
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        # Always run the full sync operation
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          OPERATION="${{ github.event.inputs.operation }}"
        else
          OPERATION="all"
        fi
        
        echo "Running operation: $OPERATION"
        node scripts/process-all.js $OPERATION
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sync-logs-${{ github.run_id }}
        path: logs/
        retention-days: 7